### ISSUE TITLE
No need to set instance variable that is used only within the method

### ISSUE THREAD

**Issue by jeremyf** [sudo-chess/chess-app#49]
In the given method, there is no need to set an instance variable of `@current_game`. The `@current_game` instance variables is used only within the scope of the method. It can instead be a local variable (e.g. `current_game = self.game`). However, even that is not needed. You can instead do

```ruby
  def move_to!(new_x, new_y)
    # Note this is a refactor of the existing behavior. However, what happens when you don't find a piece there (e.g. `target` is nil)?
    target = game.pieces.where(position_x: new_x, position_y: new_y)[0]

    if target.color != self.color
      target.update_attributes(position_x: nil, position_y: nil)
      self.update_attributes(position_x: new_x, position_y: new_y)
    end
  end
```

https://github.com/sudo-chess/chess-app/blob/5c4e432f1a559216b74de68e256ba7d4af010376/app/models/piece.rb#L14

**Comment by guillaumebihet** [comment]
Very true, refactored. 
Thanks!
