### ISSUE TITLE
Surprising instance variable name in GamesController

### ISSUE THREAD

**Issue by jeremyf** [sudo-chess/chess-app#64]
When looking at `GamesController#show` action, I was assuming that the instance variable would be named `@game` to reflect a single game. Convention is that a Rails controller's name is plural (e.g. `GamesController`), and collection-type actions instance variables are plural (e.g. `@games` for the `index` action) and member-type actions use singular instance variables (e.g. `@game` for the `show` action). Collection-type actions are ones that happen on all (or a subset of all) of the games.

Please consider renaming the instance variables to reflect this:

| Action | Variable Name |
-|-
show | `@game`
index | `@games`
pending | `@games`
playing | `@games`
complete | `@games`

https://github.com/sudo-chess/chess-app/blob/72dee83767bf2ed17c634df4ec79898e6108d9d9/app/controllers/games_controller.rb#L9

**Comment by guillaumebihet** [comment]
good point, no need to add "local_", thanks!
