### ISSUE TITLE
Unnecessary number of pieces being checked.

### ISSUE THREAD

**Issue by cxm6467** [sudo-chess/chess-app#89]
Do all pieces need to be checked or just kings?

https://github.com/sudo-chess/chess-app/blob/9609273dcbde8457e205d83ffc598f7bb2f213a8/app/models/piece.rb#L126

**Comment by cxm6467** [comment]
A king is the only piece that can be in check.  We should check if the enemy piece can move to the king's spot via a valid move.  If they can, it's in check if not it isn't.

Lastly, a king can't put another king in check.  If there aren't any other pieces besides kings, it is a stalemate.

**Comment by KyleDuca** [comment]
The method is doing what you are suggesting in your comment. It goes though ever piece that is not the current players piece and checking:

if enemy.valid_move?(x,y)

The thing with is_in_check? is that you need to call it like king.is_in_check? 
It's not restricted to kings, so you could call it on any piece such as rook.is_in_check? so maybe I should have given it a better name.
